// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string):Promise<main.AddProjectResult>;

export function DetectDevUrl(arg1:string):Promise<string>;

export function GetAllStatuses():Promise<Record<string, main.ProcessStatus>>;

export function GetAvailableEditors():Promise<Array<main.EditorInfo>>;

export function GetProjects():Promise<Array<main.ProjectConfig>>;

export function GetTheme():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<main.OpenInBrowserResult>;

export function OpenInEditor(arg1:string,arg2:string):Promise<main.OpenInEditorResult>;

export function RemoveProject(arg1:string):Promise<void>;

export function ReorderProjects(arg1:Array<main.ProjectConfig>):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function StartProject(arg1:string):Promise<main.StartProjectResult>;

export function StopProject(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:main.ProjectConfigUpdate):Promise<void>;
